"""Init

Revision ID: 84285b792f88
Revises: ecbda64bb630
Create Date: 2023-04-11 19:27:56.131458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84285b792f88'
down_revision = 'ecbda64bb630'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
